-- ╔══════════════════════════════════════════════════════════════════════╗
-- ║              QURAN DATABASE — SQL SCHEMA TEMPLATE                    ║
-- ║      Arabic (Uthmani Script) + English (Saheeh International)        ║
-- ║      114 Surahs · 6,236 Verses · Hafs an Asim                        ║
-- ║      Compatible: MySQL · PostgreSQL · SQLite · MariaDB                ║
-- ╚══════════════════════════════════════════════════════════════════════╝

-- ─────────────────────────────────────────────────────────────────────────
-- HOW TO USE
-- ─────────────────────────────────────────────────────────────────────────
-- 1. Run this schema file first to create tables and indexes.
-- 2. Use the Quran Downloader React app to generate quran.sql with full data.
-- 3. Import: sqlite3 quran.db < quran.sql
--            mysql -u root -p quran < quran.sql
--            psql -d quran -f quran.sql
-- ─────────────────────────────────────────────────────────────────────────

-- ═══════════════════════════════════════════════════════════════════════
-- TABLE: surahs
-- ═══════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS surahs (
    id                  INTEGER       PRIMARY KEY,
    number              INTEGER       NOT NULL UNIQUE,
    name_arabic         TEXT          NOT NULL,       -- Arabic name (Unicode)
    name_english        TEXT          NOT NULL,       -- Transliterated name
    name_english_meaning TEXT,                        -- English meaning
    total_verses        INTEGER       NOT NULL,
    revelation_type     TEXT          CHECK(revelation_type IN ('Meccan', 'Medinan'))
);

-- ═══════════════════════════════════════════════════════════════════════
-- TABLE: verses
-- ═══════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS verses (
    id                  INTEGER       PRIMARY KEY AUTOINCREMENT,
    surah_number        INTEGER       NOT NULL REFERENCES surahs(number) ON DELETE CASCADE,
    ayah_number         INTEGER       NOT NULL,
    arabic              TEXT          NOT NULL,       -- Uthmani Arabic text
    english             TEXT,                         -- Saheeh International English
    UNIQUE(surah_number, ayah_number)
);

-- ═══════════════════════════════════════════════════════════════════════
-- INDEXES
-- ═══════════════════════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_verses_surah     ON verses(surah_number);
CREATE INDEX IF NOT EXISTS idx_verses_ayah      ON verses(ayah_number);
CREATE INDEX IF NOT EXISTS idx_surahs_type      ON surahs(revelation_type);

-- Full-text search (SQLite only — remove for MySQL/PostgreSQL)
-- CREATE VIRTUAL TABLE IF NOT EXISTS verses_fts USING fts5(
--     arabic, english, content='verses', content_rowid='id'
-- );

-- ═══════════════════════════════════════════════════════════════════════
-- SAMPLE QUERIES
-- ═══════════════════════════════════════════════════════════════════════

-- ── Get all verses of a specific surah ──────────────────────────────
-- SELECT v.ayah_number, v.arabic, v.english
-- FROM verses v
-- WHERE v.surah_number = 1
-- ORDER BY v.ayah_number;

-- ── Get surah with verse count ───────────────────────────────────────
-- SELECT s.number, s.name_arabic, s.name_english, s.total_verses
-- FROM surahs s
-- ORDER BY s.number;

-- ── Search English translation ────────────────────────────────────────
-- SELECT s.number, s.name_english, v.ayah_number, v.arabic, v.english
-- FROM verses v
-- JOIN surahs s ON v.surah_number = s.number
-- WHERE v.english LIKE '%mercy%'
-- ORDER BY s.number, v.ayah_number;

-- ── Count Meccan vs Medinan surahs ───────────────────────────────────
-- SELECT revelation_type, COUNT(*) AS surah_count,
--        SUM(total_verses) AS verse_count
-- FROM surahs
-- GROUP BY revelation_type;

-- ── Get a random verse ──────────────────────────────────────────────
-- SELECT s.name_english, v.ayah_number, v.arabic, v.english
-- FROM verses v
-- JOIN surahs s ON v.surah_number = s.number
-- ORDER BY RANDOM() LIMIT 1;

-- ── Get the longest surah ────────────────────────────────────────────
-- SELECT number, name_english, total_verses
-- FROM surahs
-- ORDER BY total_verses DESC
-- LIMIT 1;

-- ── Get all Meccan surahs with their verse counts ────────────────────
-- SELECT number, name_arabic, name_english, total_verses
-- FROM surahs
-- WHERE revelation_type = 'Meccan'
-- ORDER BY total_verses DESC;

-- ─────────────────────────────────────────────────────────────────────────
-- NOTE: This is the schema template only.
-- Full INSERT data is generated by the Quran Downloader app.
-- ─────────────────────────────────────────────────────────────────────────
